///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModel {
/*
{
  "message": "Giriş başarılı",
  "token": "8|kjYun1mMv7zHCEsNQxm3DMrati8VRgHhMIVLKhFn5df3c4f4"
} 
*/

  String? message;
  String? token;

  LoginModel({
    this.message,
    this.token,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['token'] = token;
    return data;
  }
}
