///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AuthResponse {
/*
{
  "message": "Giriş başarılı",
  "token": "8|kjYun1mMv7zHCEsNQxm3DMrati8VRgHhMIVLKhFn5df3c4f4"
} 
*/

  String message;
  String token;

  AuthResponse({
    required this.message,
    required this.token,
  });
  

}
