///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductModelCategoriesProducts {
/*
{
  "id": "96b74539-ae2e-4c7d-a378-94d8e4abebe4",
  "category_id": "6096fd9b-88c3-47f3-a552-edabc646eb38",
  "name": "Torku Sucuk Vakum 225 G",
  "barcode": "8680181001984",
  "image": "productImages/8680181001984.jpeg",
  "created_at": "2023-09-08T20:50:26.000000Z",
  "updated_at": "2023-09-08T21:03:42.000000Z"
}
*/

  String? id;
  String? categoryId;
  String? name;
  String? barcode;
  String? image;
  String? createdAt;
  String? updatedAt;

  ProductModelCategoriesProducts({
    this.id,
    this.categoryId,
    this.name,
    this.barcode,
    this.image,
    this.createdAt,
    this.updatedAt,
  });
  ProductModelCategoriesProducts.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    categoryId = json['category_id']?.toString();
    name = json['name']?.toString();
    barcode = json['barcode']?.toString();
    image = json['image']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['category_id'] = categoryId;
    data['name'] = name;
    data['barcode'] = barcode;
    data['image'] = image;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class ProductModelCategories {
/*
{
  "id": "6096fd9b-88c3-47f3-a552-edabc646eb38",
  "name": "Et, Tavuk, Balık",
  "image": "",
  "created_at": "2023-09-08T20:34:51.000000Z",
  "updated_at": "2023-09-08T20:38:25.000000Z",
  "products": [
    {
      "id": "96b74539-ae2e-4c7d-a378-94d8e4abebe4",
      "category_id": "6096fd9b-88c3-47f3-a552-edabc646eb38",
      "name": "Torku Sucuk Vakum 225 G",
      "barcode": "8680181001984",
      "image": "productImages/8680181001984.jpeg",
      "created_at": "2023-09-08T20:50:26.000000Z",
      "updated_at": "2023-09-08T21:03:42.000000Z"
    }
  ]
}
*/

  String? id;
  String? name;
  String? image;
  String? createdAt;
  String? updatedAt;
  List<ProductModelCategoriesProducts>? products;

  ProductModelCategories({
    this.id,
    this.name,
    this.image,
    this.createdAt,
    this.updatedAt,
    this.products,
  });
  ProductModelCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    image = json['image']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    if (json['products'] != null) {
      final v = json['products'];
      final arr0 = <ProductModelCategoriesProducts>[];
      v.forEach((v) {
        arr0.add(ProductModelCategoriesProducts.fromJson(v));
      });
      products = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (products != null) {
      final v = products;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['products'] = arr0;
    }
    return data;
  }
}

class ProductModel {
/*
{
  "categories": [
    {
      "id": "6096fd9b-88c3-47f3-a552-edabc646eb38",
      "name": "Et, Tavuk, Balık",
      "image": "",
      "created_at": "2023-09-08T20:34:51.000000Z",
      "updated_at": "2023-09-08T20:38:25.000000Z",
      "products": [
        {
          "id": "96b74539-ae2e-4c7d-a378-94d8e4abebe4",
          "category_id": "6096fd9b-88c3-47f3-a552-edabc646eb38",
          "name": "Torku Sucuk Vakum 225 G",
          "barcode": "8680181001984",
          "image": "productImages/8680181001984.jpeg",
          "created_at": "2023-09-08T20:50:26.000000Z",
          "updated_at": "2023-09-08T21:03:42.000000Z"
        }
      ]
    }
  ],
  "total": 18,
  "perPage": 10,
  "page": 1
} 
*/

  List<ProductModelCategories>? categories;
  int? total;
  int? perPage;
  int? page;

  ProductModel({
    this.categories,
    this.total,
    this.perPage,
    this.page,
  });
  ProductModel.fromJson(Map<String, dynamic> json) {
    if (json['categories'] != null) {
      final v = json['categories'];
      final arr0 = <ProductModelCategories>[];
      v.forEach((v) {
        arr0.add(ProductModelCategories.fromJson(v));
      });
      categories = arr0;
    }
    total = json['total']?.toInt();
    perPage = json['perPage']?.toInt();
    page = json['page']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['categories'] = arr0;
    }
    data['total'] = total;
    data['perPage'] = perPage;
    data['page'] = page;
    return data;
  }
}

class SoldListing {
  String? id;
  String? productId;
  String? marketId;
  double? stockCount;
  double? unitCost;
  double? taxRate;
  double? profitRate;
  double? totalPrice;
  String? createdAt;
  String? updatedAt;
  Product? product;

  SoldListing({
    this.id,
    this.productId,
    this.marketId,
    this.stockCount,
    this.unitCost,
    this.taxRate,
    this.profitRate,
    this.totalPrice,
    this.createdAt,
    this.updatedAt,
    this.product,
  });

  factory SoldListing.fromJson(Map<String, dynamic> json) {
    return SoldListing(
      id: json['id']?.toString(),
      productId: json['product_id']?.toString(),
      marketId: json['market_id']?.toString(),
      stockCount: json['stock_count']?.toInt(),
      unitCost: json['unit_cost']?.toDouble(),
      taxRate: json['tax_rate']?.toInt(),
      profitRate: json['profit_rate']?.toInt(),
      totalPrice: json['total_price']?.toDouble(),
      createdAt: json['created_at']?.toString(),
      updatedAt: json['updated_at']?.toString(),
      product: Product.fromJson(json['product']),
    );
  }
}

class Product {
  String? id;
  String? categoryId;
  String? name;
  String? barcode;
  String? image;
  String? createdAt;
  String? updatedAt;

  Product({
    this.id,
    this.categoryId,
    this.name,
    this.barcode,
    this.image,
    this.createdAt,
    this.updatedAt,
  });

  factory Product.fromJson(Map<String, dynamic> json) {
    return Product(
      id: json['id']?.toString(),
      categoryId: json['category_id']?.toString(),
      name: json['name']?.toString(),
      barcode: json['barcode']?.toString(),
      image: json['image'].toString(),
      createdAt: json['created_at']?.toString(),
      updatedAt: json['updated_at']?.toString(),
    );
  }
}

class ProductCategory {
  final String id;
  final String name;
  final String image;
  final String createdAt;
  final String updatedAt;

  ProductCategory({
    required this.id,
    required this.name,
    required this.image,
    required this.createdAt,
    required this.updatedAt,
  });

  factory ProductCategory.fromJson(Map<String, dynamic> json) {
    return ProductCategory(
      id: json['id'] ?? '',
      name: json['name'] ?? '',
      image: json['image'] ?? '',
      createdAt: json['created_at'] ?? '',
      updatedAt: json['updated_at'] ?? '',
    );
  }
}

class ProductListing {
  final String id;
  final String categoryId;
  final String name;
  final String barcode;
  final String image;
  final String createdAt;
  final String updatedAt;
  final ProductCategory category;

  ProductListing({
    required this.id,
    required this.categoryId,
    required this.name,
    required this.barcode,
    required this.image,
    required this.createdAt,
    required this.updatedAt,
    required this.category,
  });

  factory ProductListing.fromJson(Map<String, dynamic> json) {
    return ProductListing(
      id: json['id'] ?? '',
      categoryId: json['category_id'] ?? '',
      name: json['name'] ?? '',
      barcode: json['barcode'] ?? '',
      image: json['image'] ?? '',
      createdAt: json['created_at'] ?? '',
      updatedAt: json['updated_at'] ?? '',
      category: ProductCategory.fromJson(json['category'] ?? {}),
    );
  }
}
