///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductRetailPrices {
/*
{
  "id": "96b74539-ae2e-4c7d-a378-94d8e4abebe4",
  "category_id": "6096fd9b-88c3-47f3-a552-edabc646eb38",
  "name": "Torku Sucuk Vakum 225 G",
  "barcode": "8680181001984",
  "image": "productImages/8680181001984.jpeg",
  "created_at": "2023-09-08T20:50:26.000000Z",
  "updated_at": "2023-09-08T21:03:42.000000Z"
}
*/

  String? id;
  String? categoryId;
  String? name;
  String? barcode;
  String? image;
  String? createdAt;
  String? updatedAt;

  ProductRetailPrices({
    this.id,
    this.categoryId,
    this.name,
    this.barcode,
    this.image,
    this.createdAt,
    this.updatedAt,
  });
  ProductRetailPrices.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    categoryId = json['category_id']?.toString();
    name = json['name']?.toString();
    barcode = json['barcode']?.toString();
    image = json['image']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['category_id'] = categoryId;
    data['name'] = name;
    data['barcode'] = barcode;
    data['image'] = image;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

// iç kısım
class ProductRetailProductRetailPrices {
/*
{
  "id": "c4c10d6d-2e45-4b6a-af2a-a1c65c27dc9d",
  "product_id": "96b74539-ae2e-4c7d-a378-94d8e4abebe4",
  "retailer_name": "Özdilek Hipermarketleri",
  "price": 106,
  "data_date": "2023-07-28 16:51:00",
  "created_at": "2023-09-08T23:05:21.000000Z",
  "updated_at": "2023-09-08T23:05:21.000000Z",
  "product": {
    "id": "96b74539-ae2e-4c7d-a378-94d8e4abebe4",
    "category_id": "6096fd9b-88c3-47f3-a552-edabc646eb38",
    "name": "Torku Sucuk Vakum 225 G",
    "barcode": "8680181001984",
    "image": "productImages/8680181001984.jpeg",
    "created_at": "2023-09-08T20:50:26.000000Z",
    "updated_at": "2023-09-08T21:03:42.000000Z"
  }
}
*/

  String? id;
  String? productId;
  String? retailerName;
  int? price;
  String? dataDate;
  String? createdAt;
  String? updatedAt;
  ProductRetailPrices? product;

  ProductRetailProductRetailPrices({
    this.id,
    this.productId,
    this.retailerName,
    this.price,
    this.dataDate,
    this.createdAt,
    this.updatedAt,
    this.product,
  });
  ProductRetailProductRetailPrices.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    productId = json['product_id']?.toString();
    retailerName = json['retailer_name']?.toString();
    price = json['price']?.toInt();
    dataDate = json['data_date']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    product = (json['product'] != null)
        ? ProductRetailPrices.fromJson(json['product'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['product_id'] = productId;
    data['retailer_name'] = retailerName;
    data['price'] = price;
    data['data_date'] = dataDate;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (product != null) {
      data['product'] = product?.toJson();
    }
    return data;
  }
}

class ProductRetail {
/*
{
  "ProductRetailPrices": [
    {
      "id": "c4c10d6d-2e45-4b6a-af2a-a1c65c27dc9d",
      "product_id": "96b74539-ae2e-4c7d-a378-94d8e4abebe4",
      "retailer_name": "Özdilek Hipermarketleri",
      "price": 106,
      "data_date": "2023-07-28 16:51:00",
      "created_at": "2023-09-08T23:05:21.000000Z",
      "updated_at": "2023-09-08T23:05:21.000000Z",
      "product": {
        "id": "96b74539-ae2e-4c7d-a378-94d8e4abebe4",
        "category_id": "6096fd9b-88c3-47f3-a552-edabc646eb38",
        "name": "Torku Sucuk Vakum 225 G",
        "barcode": "8680181001984",
        "image": "productImages/8680181001984.jpeg",
        "created_at": "2023-09-08T20:50:26.000000Z",
        "updated_at": "2023-09-08T21:03:42.000000Z"
      }
    }
  ]
}
*/

  List<ProductRetailProductRetailPrices>? productRetailPrices;

  ProductRetail({
    this.productRetailPrices,
  });
  ProductRetail.fromJson(Map<String, dynamic> json) {
    if (json['productRetailPrices'] != null) {
      final v = json['productRetailPrices'];
      final arr0 = <ProductRetailProductRetailPrices>[];
      v.forEach((v) {
        arr0.add(ProductRetailProductRetailPrices.fromJson(v));
      });
      productRetailPrices = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (productRetailPrices != null) {
      final v = productRetailPrices;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['productRetailPrices'] = arr0;
    }
    return data;
  }
}
