///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UsersModels {
/*
{
  "id": "0535a220-505c-4f0f-b250-a6cd9a48ea22",
  "name": "Market isim",
  "image": null,
  "address": "Istabul",
  "created_at": "2023-09-08T01:56:06.000000Z",
  "updated_at": "2023-09-08T01:56:06.000000Z"
}
*/

  String? id;
  String? name;
  String? image;
  String? address;
  String? createdAt;
  String? updatedAt;

  UsersModels({
    this.id,
    this.name,
    this.image,
    this.address,
    this.createdAt,
    this.updatedAt,
  });
  UsersModels.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    image = json['image']?.toString();
    address = json['address']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['address'] = address;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class UsersModelsListing {
/*
{
  "id": "268f48af-5aec-4bc1-9a50-047a3bc22b2d",
  "market_id": "0535a220-505c-4f0f-b250-a6cd9a48ea22",
  "name": "admin",
  "email": "admin@rahatsat.com",
  "email_verified_at": null,
  "is_admin": 1,
  "is_market_owner": 1,
  "is_market_staff": 0,
  "created_at": "2023-09-08T01:55:31.000000Z",
  "updated_at": "2023-10-09T11:24:15.000000Z",
  "market": {
    "id": "0535a220-505c-4f0f-b250-a6cd9a48ea22",
    "name": "Market isim",
    "image": null,
    "address": "Istabul",
    "created_at": "2023-09-08T01:56:06.000000Z",
    "updated_at": "2023-09-08T01:56:06.000000Z"
  }
}
*/

  String? id;
  String? marketId;
  String? name;
  String? email;
  String? emailVerifiedAt;
  int? isAdmin;
  int? isMarketOwner;
  int? isMarketStaff;
  String? createdAt;
  String? updatedAt;
  UsersModels? market;

  UsersModelsListing({
    this.id,
    this.marketId,
    this.name,
    this.email,
    this.emailVerifiedAt,
    this.isAdmin,
    this.isMarketOwner,
    this.isMarketStaff,
    this.createdAt,
    this.updatedAt,
    this.market,
  });
  UsersModelsListing.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    marketId = json['market_id']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    emailVerifiedAt = json['email_verified_at']?.toString();
    isAdmin = json['is_admin']?.toInt();
    isMarketOwner = json['is_market_owner']?.toInt();
    isMarketStaff = json['is_market_staff']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    market = (json['market'] != null) ? UsersModels.fromJson(json['market']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['market_id'] = marketId;
    data['name'] = name;
    data['email'] = email;
    data['email_verified_at'] = emailVerifiedAt;
    data['is_admin'] = isAdmin;
    data['is_market_owner'] = isMarketOwner;
    data['is_market_staff'] = isMarketStaff;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (market != null) {
      data['market'] = market?.toJson();
    }
    return data;
  }
}

class UsersModel {
/*
{
  "users": [
    {
      "id": "268f48af-5aec-4bc1-9a50-047a3bc22b2d",
      "market_id": "0535a220-505c-4f0f-b250-a6cd9a48ea22",
      "name": "admin",
      "email": "admin@rahatsat.com",
      "email_verified_at": null,
      "is_admin": 1,
      "is_market_owner": 1,
      "is_market_staff": 0,
      "created_at": "2023-09-08T01:55:31.000000Z",
      "updated_at": "2023-10-09T11:24:15.000000Z",
      "market": {
        "id": "0535a220-505c-4f0f-b250-a6cd9a48ea22",
        "name": "Market isim",
        "image": null,
        "address": "Istabul",
        "created_at": "2023-09-08T01:56:06.000000Z",
        "updated_at": "2023-09-08T01:56:06.000000Z"
      }
    }
  ],
  "total": 2,
  "perPage": 10,
  "page": 1
}
*/

  List<UsersModelsListing>? users;
  int? total;
  int? perPage;
  int? page;

  UsersModel({
    this.users,
    this.total,
    this.perPage,
    this.page,
  });

  UsersModel.fromJson(Map<String, dynamic> json) {
  if (json['users'] != null) {
  final v = json['users'];
  final arr0 = <UsersModelsListing>[];
  v.forEach((v) {
  arr0.add(UsersModelsListing.fromJson(v));
  });
    users = arr0;
    }
    total = json['total']?.toInt();
    perPage = json['perPage']?.toInt();
    page = json['page']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (users != null) {
      final v = users;
      final arr0 = [];
  v?.forEach((v) {
  arr0.add(v.toJson());
  });
      data['users'] = arr0;
    }
    data['total'] = total;
    data['perPage'] = perPage;
    data['page'] = page;
    return data;
  }
}
